package com.devluis.entity;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.OffsetDateTime;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// A weekly recurring generation PATTERN for "administracion/horarios": what
// hours, on which weekday, at what slot interval, this (establishment,
// service, doctor-or-pool) combination is normally open. This is the last of
// the 32 admin destinations, and it is the piece that turns "the clinic's
// opening hours" from a hardcoded landing-page string into DATA that
// ScheduleService#generateSchedulesFromTemplates (and the public read — see
// GlobalConfig) can read.
//
// SCOPING — required vs optional, decided by mirroring exactly what
// GenerateSchedulesBody/ScheduleService#generateSchedules ALREADY require or
// allow for one-off generation, since a template must never be able to
// describe something the generator itself could not produce:
// - stablishment: REQUIRED. Every Schedule this system has ever produced is
// establishment-scoped, and generateSchedules already treats
// stablishmentId as @NotNull. Unlike Holiday (where NULL legitimately
// means "every establishment" for a literal calendar fact like a
// national holiday), operating HOURS have no natural clinic-wide
// default — site A and site B can simply run different schedules — so
// there is no "global" template here.
// - servicio: REQUIRED, for the same reason: serviceId is @NotNull on
// GenerateSchedulesBody, and every Schedule this generator can create
// always carries a concrete service. A template could not describe
// anything the generator itself is not capable of producing without one.
// - doctor: OPTIONAL. Mirrors GenerateSchedulesBody#doctorId already being
// nullable — "pool" slots (any doctor covering this service at this
// establishment) are an existing, first-class concept in this codebase,
// not something invented for this feature.
//
// OVERLAP — same precedent as Promotion (see its docblock): two templates
// that would generate a contradictory pattern are REJECTED at write time
// instead of requiring the generator to pick a tie-breaker later.
// ScheduleTemplateService#rejectIfOverlapping enforces two separate scopes,
// mirroring the two separate "is this slot already taken" checks
// ScheduleService itself already makes for doctor-bound vs pool slots:
// - doctor-bound templates: at most one per (doctor, dayOfWeek) with
// overlapping [startTime, endTime) AND overlapping [validFrom,
// validUntil] — a doctor cannot be double-templated into two
// establishments/services at the same weekly instant, regardless of
// which establishment/service each template names.
// - pool templates (doctor IS NULL): at most one per (stablishment,
// servicio, dayOfWeek) with the same time/validity overlap rule — two
// pool templates covering the same slot would otherwise force the
// generator to pick which slotIntervalMinutes wins in the overlapping
// window, exactly the tie-breaker Promotion's precedent avoids.
//
// PRE-EXISTING SLOTS ON UPDATE/DELETE — the decision explicitly flagged as
// pending. Chosen: a ScheduleTemplate is a PURE GENERATOR INPUT. Narrowing
// or deleting a template affects ONLY future
// generateSchedulesFromTemplates calls; it NEVER touches an already-created
// Schedule row, free or booked. This is a deliberate DEPARTURE from the
// Holiday/TimeOff precedent (which DOES sweep existing schedules to
// STATUS_UNAVAILABLE), for reasons that do not apply here:
// 1. No FK links a Schedule back to the ScheduleTemplate that produced it
// (same non-goal as Holiday/TimeOff), but UNLIKE Holiday ("this date is
// now a holiday") or TimeOff ("this doctor is away these dates") — both
// unambiguous FACTS about a concrete date that directly invalidate any
// schedule on file for it — a template's (establishment, service,
// doctor, weekday, hour) tuple is only a PROBABILISTIC match against an
// existing Schedule row, which could equally have been hand-created via
// POST /api/schedules, generated by the parameter-driven path, or by a
// since-replaced template. Auto-blocking on that inference risks
// disabling capacity the admin never intended to touch.
// 2. A template describes recurring INTENT for FUTURE generation, not a
// fact about reality today — narrowing 08:00-17:00 to 08:00-12:00 does
// not assert "the clinic is closed 12:00-17:00" (nothing changed about
// whether the establishment is open then), only that the admin no
// longer wants THAT PATTERN auto-generating slots for that window going
// forward.
// 3. Consistency with the parameter-driven path it wraps: calling
// generateSchedules(GenerateSchedulesBody) twice with different
// intervalMinutes/date values already never edits or deletes a
// previously generated Schedule. A template changing is the same class
// of event — different parameters for the NEXT generation call — so
// giving the template-driven path a more invasive side effect than the
// parameter-driven path it is built on top of would be an unjustified,
// surprising asymmetry.
// A stronger guarantee falls out of this for free: since no ScheduleTemplate
// mutation ever reads or writes a Schedule row, a booked turn can never be
// affected by editing or deleting a template — not merely "never destroyed,"
// never touched at all. See apply report for the full writeup.
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Table(name = "schedule_templates")
@Entity
public class ScheduleTemplate {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "stablishment_id", nullable = false)
  private Stablishment stablishment;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "service_id", nullable = false)
  private Servicio servicio;

  // NULL = pool slot, not tied to one specific doctor — see docblock.
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "doctor_id")
  private Doctor doctor;

  /**
   * El consultorio por defecto de esta jornada. Lo asigna un ROLE_ADMIN: las
   * escrituras de esta entidad ya estan cerradas a ROLE_ADMIN en GlobalConfig,
   * asi que el medico no puede asignarse el suyo ni por API.
   *
   * Vive aca y no en Doctor porque hacen falta TRES datos para que la frase
   * cierre: medico + servicio + SEDE. `Doctor.stablishments` es @ManyToMany,
   * y "Consultorio 3" solo significa algo dentro de una sede. Esta plantilla
   * ya tiene los tres, mas el dia y el horario, asi que el mismo medico
   * puede estar en el 3 los lunes y en el 5 los miercoles.
   *
   * NULLABLE: las plantillas que ya existen no tienen consultorio y siguen
   * siendo validas. Al llamar un turno el operador puede elegirlo igual.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "consultorio_id")
  private Consultorio consultorio;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private DayOfWeek dayOfWeek;

  @Column(nullable = false)
  private LocalTime startTime;

  @Column(nullable = false)
  private LocalTime endTime;

  @Column(nullable = false)
  private Integer slotIntervalMinutes;

  @Column(nullable = false)
  private LocalDate validFrom;

  // NULL = open-ended (no expiration).
  private LocalDate validUntil;

  @CreationTimestamp
  @Column(columnDefinition = "timestamptz")
  private OffsetDateTime createdAt;
}
